#!/bin/bash

# Проверка количества аргументов
if [ "$#" -ne 3 ]; then
    echo "Использование: $0 Имя пользователя Пароль IP-подключения IP-записи"
    exit 1
fi

# Имя пользователя
username=$1

# IP-адрес для подключения
IP1=$2

# IP-адрес для записи в файл
IP2=$3

# Проверка IP-адресов
if ! [[ $IP1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "IP1 не является действительным IP-адресом"
    exit 1
fi

if ! [[ $IP2 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "IP2 не является действительным IP-адресом"
    exit 1
fi

# Команда для изменения файла
read -r -d '' command <<EOF
sudo bash -c 'cat > /etc/netplan/00-installer-config.yaml << EOL
# This is the network config written by 'subiquity'
network:
  ethernets:
    eth0:
      addresses:
        - $IP2/24
      routes:
        - to: 0.0.0.0/0
          via: 192.168.0.1
      nameservers:
          addresses: [8.8.8.8, 8.8.4.4]
  version: 2
EOL'
EOF

# Подключение по SSH и выполнение команды
ssh "$username@$IP1" "$command"

command="sudo netplan apply"

ssh "$username@$IP1" "$command"
