---
- name: Remove Node Exporter
  hosts: all
  become: true
  tasks:
    - name: Stop Node Exporter service
      systemd:
        name: node-exporter
        state: stopped
        enabled: no

    - name: Remove Node Exporter binary
      file:
        path: /usr/local/bin/node_exporter
        state: absent

    - name: Remove Node Exporter systemd service
      file:
        path: /etc/systemd/system/node-exporter.service
        state: absent

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Remove leftover files (if any)
      file:
        path: /tmp/node_exporter*
        state: absent
