---
- name: Установка Kubernetes на Ubuntu Server 22.04 LTS
  hosts: master_servers, worker_servers
  become: true

  tasks:
    - name: Отключаем включение swap после перезагрузки
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^(\/swap\.img.*)'
        line: '#\1'
        backrefs: yes
      become: true

    - name: Отключаем swap
      ansible.builtin.command:
        cmd: swapoff -a

    - name: Загрузка модулей ядра
      lineinfile:
        dest: /etc/modules-load.d/containerd.conf
        line: "{{ item }}"
        create: yes
      with_items:
        - overlay
        - br_netfilter

    - name: Загрузка модуля overlay
      command: modprobe overlay

    - name: Загрузка модуля br_netfilter
      command: modprobe br_netfilter

    - name: Установка параметров ядра для Kubernetes
      lineinfile:
        dest: /etc/sysctl.d/kubernetes.conf
        line: "{{ item }}"
        create: yes
      with_items:
        - "net.bridge.bridge-nf-call-ip6tables = 1"
        - "net.bridge.bridge-nf-call-iptables = 1"
        - "net.ipv4.ip_forward = 1"

    - name: Применение настроек ядра
      command: sysctl --system

    - name: Добавление GPG ключа репозитория Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Получение версии Ubuntu
      command: lsb_release -cs
      register: ubuntu_version

    - name: Вывод версии Ubuntu
      debug:
        var: ubuntu_version.stdout

    - name: Подключение репозитория Docker
      become: true
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"

    - name: Обновление локального индекса пакетов
      apt:
        update_cache: yes

    - name: Установка пакетов для Kubernetes
      apt:
        name:
          - curl
          - gnupg2
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - containerd.io
        state: present

    - name: Настройка файла конфигурации containerd
      shell: "containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1"

    - name: Изменение настроек containerd
      become: true
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Перезапуск containerd
      service:
        name: containerd
        state: restarted
        enabled: true

    - name: Включение автозапуска сервиса containerd
      become: true
      systemd:
        name: containerd
        enabled: yes

    - name: Добавление GPG ключа репозитория Kubernetes
      shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
      changed_when: false

    - name: Добавление репозитория Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes

    - name: Обновление локального индекса пакетов
      apt:
        update_cache: yes

    - name: Установка пакетов kubelet, kubeadm, kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: latest

    - name: Запрет автоматического обновления и удаления пакетов
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
