---
- name: Настройка Kubernetes на рабочих-нодах
  hosts: worker_servers, master_servers

  tasks:
    - name: Сброс состояния рабочих-нод
      command: kubeadm reset --force
      become: true
#      ignore_errors: true
      when: "'worker_servers' in group_names"

    - name: Запуск команды kubeadm token create --print-join-command
      shell: kubeadm token create --print-join-command
      register: output
      become: true
      when: inventory_hostname == groups['master_servers'][0]

    - name: Сохранение команды в переменной
      set_fact:
        join_command: "{{ output.stdout }}"
      when: inventory_hostname == groups['master_servers'][0]

    - name: Присоединение остальных рабочих-нод
      shell: "{{ hostvars[groups['master_servers'][0]].join_command }}"
      args:
        executable: /bin/bash
      become: true
      when: "'worker_servers' in group_names"
