- name: Настройка пользователя ansible на сервере
  hosts: all
#  remote_user: vlad
  become_user: vlad
  become: true
  vars:
    ansible_user: ansible
    ssh_key_path: ~/.ssh/id_rsa_ansible
  tasks:
    - name: Убедиться, что пользователь существует
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        state: present
        shell: /bin/bash

    - name: Создать .ssh директорию для пользователя
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'

    - name: Проверить, существует ли локальный SSH-ключ
      ansible.builtin.stat:
        path: "{{ ssh_key_path }}"
      register: local_ssh_key

    - name: Создать локальный SSH-ключ, если его нет
      ansible.builtin.command:
        cmd: ssh-keygen -t rsa -b 4096 -f "{{ ssh_key_path }}" -q -N ""
      when: not local_ssh_key.stat.exists

    - name: Прочитать локальный публичный ключ
      ansible.builtin.slurp:
        src: "{{ ssh_key_path }}.pub"
      register: local_ssh_pubkey

    - name: Добавить локальный публичный ключ в authorized_keys пользователя
      ansible.builtin.copy:
        content: "{{ local_ssh_pubkey.content | b64decode }}"
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Настроить sudo для пользователя ansible
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        create: yes
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        mode: '0440'
